travis:
  secure:
    BINSTAR_TOKEN: r5X2sOvmXLd5dGUIN9Kx+oKj9rffNG6XdSHiuVHcHNPCCqPmTTbO7ev6D81RAhRXnoYPXLLth3bXVMY/V0ZatB0I42rTCceqj77ZgzbsI69APhlwvM3GB4BryciUDwnhmiQTlwR5EHALzXLNck9+3ydbhZolSOoB/E2tsb1kmu5paoq4zX8IB20XDNU6AFnv6woMt/WN8P2GVoqsBk9KMVOPRQy+BCA3f6lMvlMHmM73gwOsCunlsJZfylvy8hzDh2LGvsNs4XrcmmJ6b4wdnuJQ6rgy56afms2nvf90mVJ4je7/sLgI12+5ypoqIvauqNCsmYH2rL/mhNln7Z0dFicyu7X9YvcyPM3aJ92ozpTerMaelUEEtizP+x7gZARp9LuwXInfkA3FOEm2tK2ecRxA6K9gej6DqgAXPiNpZ8BWiUYFVCDIgq4hG5PPY3UsJarJsq3k10hZtBvtRsb62S/PeeVRIli/uwDszZ3Qhz4bkopa5IiV1gZL8x5uebEF6+8vPgINAOUd5DzCYPVk0Pxpza2y7ypbj7E7zqO57WpC1xfDdB+DkKIM2FzjkkZGwMbxenUah8KvL9a64ofhEIblduZ/3fsgmFn0pBeFuxMa4El7YuC0n6DDHpDYUkxg1NO/llNM9+U7G0Wk3QFtpHvTGkejPchYgS8SxRKjspY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
