travis:
  secure:
    BINSTAR_TOKEN: aMoI+ygBwtu1vfO2c1eiwzwiAtNyskZL9Rst3mwNZsRHluzu6KQU7LvtVpBwpiEEKGeFtg8yG1uOklI29oT9WP4or6fHcRHchxuN5634NGkylCmAbPz4G0xER03LPgIlyWZTgIgtOaMOtmyOgW6FnPsJda87YzsfqVvP7Aa3Yq7g8S/FbmHRtldwKN3llxk7z5vNJ6VJOMsVlCg6i64/LZnfrtgfvJSzv7/JCInXxSqa3PK8diBWVwb7sHMOz+LTjf5ltaoX9zFml43Jr+gTqaPARMgZV6twibrune4yyu1yJP+p/6+rHkZ9IwyHrDU7A2dDdgw0UWzIvnYyg5bZUYeIJddlhyojaui53/7ClqU+7B7GhUvDB5khwonW4/aec4+6mqHiVufWWkzskixK6blwyJtqywHYplVp72m3OTBq2dq7q7qadaKv7eOaPtempD4FUOB1WK5ZiPY1m5njzCoRYKaD95t3QRGk51pIAhqcosBFyXZo9MMp3vGX2FeZpe7XtojR2KVxAFmn2lRoE2RmlTkomulkOtSWEdaVQL7xJFHV6S+MD4Bm16tSzYHOsx8tgVFFi8ykfYClfpoQmTOzgllLMecj64aAarv8t5IMDmHyenoi1xaXUaOGSctqXFQ5z3Rx1fWVXvezCKrL6HC6tBVlm0/4Ki9f2dHlzqc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
